# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-17 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '已选课',
                'verbose_name_plural': '已选课',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=128)),
                ('c_teacher', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['c_name'],
            },
        ),
        migrations.CreateModel(
            name='Inf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Course')),
            ],
            options={
                'verbose_name': '选课记录',
                'verbose_name_plural': '选课记录',
                'ordering': ['time'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='types',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('c_name', 'c_teacher')]),
        ),
        migrations.AddField(
            model_name='choice',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Course'),
        ),
    ]
