# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-18 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_choice_stu'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='left_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='max_count',
            field=models.IntegerField(default=40),
        ),
    ]
